// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package oqlexample.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the OQLExample module
	public static java.util.List<oqlexample.proxies.ExamplePersonResult> dS_ExampleOQL(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			java.util.List<IMendixObject> objs = Core.execute(context, "OQLExample.DS_ExampleOQL", params);
			java.util.List<oqlexample.proxies.ExamplePersonResult> result = null;
			if (objs != null)
			{
				result = new java.util.ArrayList<oqlexample.proxies.ExamplePersonResult>();
				for (IMendixObject obj : objs)
					result.add(oqlexample.proxies.ExamplePersonResult.initialize(context, obj));
			}
			return result;
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iVK_CreateContent(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			Core.execute(context, "OQLExample.IVK_CreateContent", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iVK_Order_CreateByPersonArticlePriceDate(IContext context, oqlexample.proxies.ExamplePerson _examplePerson)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("ExamplePerson", _examplePerson == null ? null : _examplePerson.getMendixObject());
			Core.execute(context, "OQLExample.IVK_Order_CreateByPersonArticlePriceDate", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iVK_PerformTests(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			Core.execute(context, "OQLExample.IVK_PerformTests", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iVK_Wedding(IContext context, oqlexample.proxies.ExamplePerson _examplePerson1, oqlexample.proxies.ExamplePerson _examplePerson2)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("ExamplePerson1", _examplePerson1 == null ? null : _examplePerson1.getMendixObject());
			params.put("ExamplePerson2", _examplePerson2 == null ? null : _examplePerson2.getMendixObject());
			Core.execute(context, "OQLExample.IVK_Wedding", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
}